# A generic, single database configuration.

[alembic]
# path to migration scripts. Can be overridden at runtime.
script_location = migrations

# template used to generate migration files
file_template = %%(rev)s_%%(slug)s

# representation of the database url. Set dynamically at runtime.
sqlalchemy.url = sqlite:///./storage/actionsync.db

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
